Repository WildCodeSchool/orleans-php-2003-project-aon, pull requests merged in 2020-04, with the labels that each got.

#2 Initialisation
  composer.lock
  public/assets/css/style.css
  public/assets/images/logo_AON.png
  src/View/layout.html.twig
Labels: Reviewed

#3 Us05 activity
  .gitignore
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  public/assets/images/bronzage.jpg
  public/assets/images/compete.jpg
  public/assets/images/compete2.jpg
  public/assets/images/detente.jpg
  public/assets/images/detente2.jpg
  public/assets/images/eclaboussure.jpg
  public/assets/images/ensemble.jpg
  public/assets/images/fillette.png
  public/assets/images/nager.jpeg
  public/assets/images/nageurs.jpeg
  public/assets/images/peur.jpeg
  public/assets/images/team.jpg
  public/assets/images/vert.jpg
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/ActivityManager.php
  src/View/Home/_activity.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#4 Us04
  public/assets/css/homepage_event.css
  public/assets/css/style.css
  public/assets/images/actu_nage.jpg
  public/assets/images/actu_saturday_night.jpg
  public/assets/images/actu_stage.jpg
  public/assets/images/eurocom_massy.jpg
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Home/_event.html.twig
  src/View/Home/index.html.twig
  src/View/Item/edit.html.twig
Labels: Reviewed

#6 Us01 navbar
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#8 Sp01 us07 page activity
  public/assets/css/homepage_activity.css
  public/assets/images/accueil.jpg
  src/Controller/ActivityController.php
  src/View/Activity/index.html.twig
  src/View/Home/_activity.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#7 Us06partner
  public/assets/.DS_Store
  public/assets/css/style.css
  public/assets/images/.DS_Store
  public/assets/images/CentreValDeLoireDrdjscs.jpg
  public/assets/images/LoiretVotreDepartement.png
  public/assets/images/OrleansMairie.png
  public/assets/images/RegioncentreValdeloire.jpg
  public/assets/images/nataquashop.png
  src/Controller/HomeController.php
  src/Model/PartnerManager.php
  src/View/Home/_partner.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#9 footer
  public/assets/css/style.css
  public/assets/images/logo_facebook.png
  src/View/layout.html.twig
Labels: Reviewed

#10 Fix/design adjust
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/style.css
  public/assets/icons/hamburger.png
  src/View/Activity/_activity.html.twig
  src/View/Activity/index.html.twig
  src/View/Home/_activity.html.twig
  src/View/Home/_event.html.twig
  src/View/Home/_partner.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#12 Fix/comment adjust
  public/assets/.DS_Store
  public/assets/css/homepage_activity.css
  public/assets/images/.DS_Store
  src/Controller/ActivityController.php
  src/Controller/HomeController.php
  src/Model/ActivityManager.php
  src/Model/PartnerManager.php
  src/View/Activity/_activity.html.twig
Labels: Reviewed

#13 US01 to US07
  public/assets/.DS_Store
  public/assets/css/homepage_activity.css
  public/assets/images/.DS_Store
  src/Controller/ActivityController.php
  src/Controller/HomeController.php
  src/Model/ActivityManager.php
  src/Model/PartnerManager.php
  src/View/Activity/_activity.html.twig
Labels: Reviewed

#23 Sp2 us20 event page
  public/assets/css/homepage_event.css
  public/assets/images/actu_nage.jpg
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/_event.html.twig
  src/View/Event/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#31 Sp2 fix review1
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  public/assets/images/logo_AON.png
  public/assets/images/logo_AON_fondblanc.png
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#33 Sp2US40 New graphical charter
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_partner.css
  public/assets/css/style.css
  public/assets/images/intro.jpg
  public/assets/images/turbulences2.png
  src/View/Home/_activity.html.twig
  src/View/Home/_event.html.twig
  src/View/Home/_partner.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#37 Update master
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/homepage_partner.css
  public/assets/css/style.css
  public/assets/images/actu_nage.jpg
  public/assets/images/intro.jpg
  public/assets/images/logo_AON.png
  public/assets/images/logo_AON_fondblanc.png
  public/assets/images/turbulences2.png
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/_event.html.twig
  src/View/Event/index.html.twig
  src/View/Home/_activity.html.twig
  src/View/Home/_event.html.twig
  src/View/Home/_partner.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#41 Sp2 us32 patch admin4
  .gitignore
  src/Controller/AdminController.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#42 ajout who are us
  public/assets/css/style.css
  public/assets/css/whoAreUs.css
  public/assets/images/whoAreUs.jpg
  src/Controller/WhoAreUsController.php
  src/Model/WhoAreUsManager.php
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#43 Sp2 us31 admin event edit
  public/assets/css/admin_event.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/showEvent.html.twig
Labels: Corrections done, Reviewed

#44 SP2 Dev to Master
  .gitignore
  public/assets/css/admin_event.css
  public/assets/css/style.css
  public/assets/css/whoAreUs.css
  public/assets/images/whoAreUs.jpg
  src/Controller/AdminController.php
  src/Controller/WhoAreUsController.php
  src/Model/EventManager.php
  src/Model/WhoAreUsManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/showEvent.html.twig
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#45 Sp2 us30 adding event to db
  public/assets/css/admin_event.css
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/addEvent.html.twig
  src/View/Admin/eventFormLayout.html.twig
  src/View/layout.html.twig
Labels: Reviewed, important

#46 Sp2 us33 delete event bis
  public/assets/css/style.css
  public/assets/icons/logo_delete.png
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
Labels: Conflicts, Corrections done, Reviewed

#47 Sp2/global css fix
  public/assets/css/admin_event.css
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/homepage_partner.css
  public/assets/css/style.css
  public/assets/css/whoAreUs.css
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Home/index.html.twig
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#48 SP2 - Dev to Master
  public/assets/css/admin_event.css
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/homepage_partner.css
  public/assets/css/style.css
  public/assets/css/whoAreUs.css
  public/assets/icons/logo_delete.png
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/addEvent.html.twig
  src/View/Admin/eventFormLayout.html.twig
  src/View/Home/index.html.twig
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#50 Sp3 us28 admin activity
  src/Controller/AdminController.php
  src/Model/ActivityManager.php
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/index.html.twig
Labels: Corrections done, Reviewed

#51 Sp3 us08 view activity
  public/assets/css/activity.css
  public/assets/css/style.css
  public/assets/icons/cal.png
  public/assets/icons/clock.png
  public/assets/icons/location.png
  public/assets/icons/pool.png
  src/Controller/ActivityController.php
  src/Controller/AdminController.php
  src/Model/LessonManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Home/_activity.html.twig
Labels: Reviewed

#52 Sp3 us09 choosing age class
  src/Controller/ActivityController.php
  src/Model/LessonManager.php
  src/View/Activity/showActivity.html.twig
Labels: Reviewed

#54 Sp3 css fix
  public/assets/css/activity.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/style.css
  public/assets/icons/location.png
  public/assets/images/bulles.png
  public/assets/images/detente.jpg
  src/Model/LessonManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Home/_event.html.twig
Labels: Reviewed

#55 US08 and US09
  public/assets/css/activity.css
  public/assets/css/homepage_activity.css
  public/assets/css/homepage_event.css
  public/assets/css/style.css
  public/assets/icons/cal.png
  public/assets/icons/clock.png
  public/assets/icons/location.png
  public/assets/icons/pool.png
  public/assets/images/bulles.png
  public/assets/images/detente.jpg
  src/Controller/ActivityController.php
  src/Controller/AdminController.php
  src/Model/ActivityManager.php
  src/Model/LessonManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/index.html.twig
  src/View/Home/_activity.html.twig
  src/View/Home/_event.html.twig
Labels: Reviewed
