Repository WildCodeSchool/orleans-php-2003-project-aon, pull requests merged in 2020-05, with the labels that each got.

#56 SP3US28LessonAdmin
  src/Controller/AdminController.php
  src/Model/LessonManager.php
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/index.html.twig
Labels: Reviewed

#59 Sp3 us25 add lesson
  public/assets/css/admin_lesson.css
  public/assets/css/style.css
  src/Controller/ActivityController.php
  src/Controller/AdminLessonController.php
  src/Model/AgeManager.php
  src/Model/LessonManager.php
  src/Model/PoolManager.php
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/addLesson.html.twig
  src/View/Admin/lessonFormLayout.html.twig
Labels: Reviewed

#60 Sp4 us29 activity listing for admin
  public/assets/activityImages/bronzage.jpg
  public/assets/activityImages/compete.jpg
  public/assets/activityImages/compete2.jpg
  public/assets/activityImages/detente.jpg
  public/assets/activityImages/detente2.jpg
  public/assets/activityImages/eclaboussure.jpg
  public/assets/activityImages/ensemble.jpg
  public/assets/activityImages/fillette.png
  public/assets/activityImages/nager.jpeg
  public/assets/activityImages/nageurs.jpeg
  public/assets/activityImages/peur.jpeg
  public/assets/activityImages/team.jpg
  public/assets/activityImages/vert.jpg
  src/Controller/AdminController.php
  src/Model/ActivityManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/index.html.twig
  src/View/Home/_activity.html.twig
Labels: Reviewed, important

#61 Sp4 us42 edit activities for admin
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/showActivity.html.twig
Labels: Reviewed

#64 SP4Us26edit lesson
  src/Controller/AdminLessonController.php
  src/Model/LessonManager.php
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/editLesson.html.twig
Labels: Reviewed

#66 US35WhoAreUsfixCSS
  public/assets/css/whoAreUs.css
Labels: Reviewed

#65 SP4US27DeleteLesson
  src/Controller/AdminLessonController.php
  src/Model/LessonManager.php
  src/View/Admin/_lessonAdmin.html.twig
Labels: Reviewed

#68 SP4US43_deleteActivity
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/Model/LessonManager.php
  src/View/Admin/_activityAdmin.html.twig
Labels: Corrections done, Reviewed

#70 US35WhoAreUSPatch
  public/assets/css/style.css
  public/assets/css/whoAreUs.css
  src/View/WhoAreUs/index.html.twig
Labels: Reviewed

#69 SP4US41_createActivity
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/HomeController.php
  src/View/Admin/_activityDetails.html.twig
Labels: Corrections done, Reviewed

#71 SP4US16_staticContactPage
  public/assets/css/contact.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#72 SP4US15TrainingSessionPage
  public/assets/css/stage.css
  public/assets/css/style.css
  public/assets/images/equilibre_dorsal.jpg
  public/assets/images/propulsion.jpg
  public/assets/images/respiration.jpg
  src/Controller/StageController.php
  src/Model/StageManager.php
  src/View/Stage/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#75 SP4US14Prices
  public/assets/css/prices.css
  public/assets/css/style.css
  src/Controller/AdminLessonController.php
  src/Controller/PriceController.php
  src/Model/LessonManager.php
  src/View/Price/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#76 SP4US17_deleteMessage
  src/Controller/AdminMessageController.php
Labels: Reviewed

#77 Sp4 us34linkContactFromTraineship
  src/View/Stage/index.html.twig
Labels: Reviewed

#80 SP5US13Addlinkcontact
  src/View/Activity/showActivity.html.twig
Labels: Reviewed

#82 Fix suppresion ajout event dans admin messagerie
  src/View/Admin/_messageAdmin.html.twig
Labels: Reviewed

#86 Sp5 us37 admin who are us
  public/assets/activityImages/5eb258d12f3e9.jpeg
  public/assets/activityImages/5eb2e81f7cfa4.jpg
  public/assets/activityImages/5eb8178403d52.jpeg
  public/assets/css/admin_who_are_us.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Controller/AdminWhoAreUsController.php
  src/Model/WhoAreUsManager.php
  src/View/Admin/_whoAreUsAdmin.html.twig
  src/View/Admin/index.html.twig
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
Labels: Corrections done, Reviewed

#91 SP5US13AddContactButtonV2
  public/assets/activityImages/5eb91c1e4f753.jpg
  src/View/Activity/showActivity.html.twig
Labels: Reviewed

#94 FixLessonAdmin
  src/View/Admin/_lessonAdmin.html.twig
Labels: Reviewed

#92 SP5US18 Add links
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Home/_event.html.twig
Labels: Corrections done, Reviewed

#95 Sp5 css fix
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  public/assets/icons/swimming.svg
  public/assets/icons/swimming33.svg
  public/assets/icons/swimming66.svg
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_messageAdmin.html.twig
  src/View/Admin/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#99 Sp5 form simplification
  src/Controller/AdminActivityController.php
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/activityFormLayout.html.twig
  src/View/Admin/addActivity.html.twig
  src/View/Admin/editActivity.html.twig
  src/View/Admin/formLayout.html.twig
  src/View/Admin/lessonFormLayout.html.twig
  src/View/Admin/showActivity.html.twig
Labels: Corrections done, Reviewed

#100 Sp5 css fix next step
  public/assets/css/activity.css
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  public/assets/images/bulles25-1-l.png
  public/assets/images/bulles25-2-l.png
  public/assets/images/bulles25-3-l.png
  public/assets/images/bulles25-4-l.png
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#101 Sp5 us45 add pool edit lesson
  src/Controller/AdminLessonController.php
  src/Model/LessonManager.php
  src/Model/PoolManager.php
  src/View/Admin/_lessonDetails.html.twig
Labels: Reviewed

#103 SP5 Fix homogénéisation admin who are us
  src/View/Admin/_whoAreUsAdmin.html.twig
Labels: Reviewed

#104 Sp5us18addLinkCreateEvent
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
Labels: Reviewed

#105 SP5US18 add link update event
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/_eventDetails.html.twig
Labels: Reviewed

#106 Sp5 us45addpoolCreateLesson
  src/Controller/AdminLessonController.php
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_lessonDetails.html.twig
Labels: Reviewed

#108 SP5 Fixcss admin who are us
  public/assets/activityImages/5ebb94c938c83.jpg
  src/View/Admin/_whoAreUsAdmin.html.twig
Labels: Corrections done, Reviewed

#109 SP5
  public/assets/activityImages/5eb2e81f7cfa4.jpg
  public/assets/activityImages/5eb81646b2c19.jpg
  public/assets/activityImages/5eb81689ddd92.jpeg
  public/assets/activityImages/5eb8178403d52.jpeg
  public/assets/activityImages/5eb91c1e4f753.jpg
  public/assets/activityImages/5ebb94c938c83.jpg
  public/assets/css/activity.css
  public/assets/css/admin_who_are_us.css
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  public/assets/eventImages/5eb90e3e8bf86.JPG
  public/assets/eventImages/5eb90e76f2ea9.jpg
  public/assets/eventImages/actu_nage.jpg
  public/assets/eventImages/actu_saturday_night.jpg
  public/assets/eventImages/eurocom_massy.jpg
  public/assets/eventImages/team.jpg
  public/assets/eventImages/vert.jpg
  public/assets/icons/swimming.svg
  public/assets/icons/swimming33.svg
  public/assets/icons/swimming66.svg
  public/assets/images/actu_stage.jpg
  public/assets/images/bulles25-1-l.png
  public/assets/images/bulles25-2-l.png
  public/assets/images/bulles25-3-l.png
  public/assets/images/bulles25-4-l.png
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminLessonController.php
  src/Controller/AdminWhoAreUsController.php
  src/Model/EventManager.php
  src/Model/LessonManager.php
  src/Model/PoolManager.php
  src/Model/WhoAreUsManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/_messageAdmin.html.twig
  src/View/Admin/_whoAreUsAdmin.html.twig
  src/View/Admin/activityFormLayout.html.twig
  src/View/Admin/addActivity.html.twig
  src/View/Admin/editActivity.html.twig
  src/View/Admin/eventFormLayout.html.twig
  src/View/Admin/formLayout.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/lessonFormLayout.html.twig
  src/View/Admin/showActivity.html.twig
  src/View/Admin/showEvent.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_event.html.twig
  src/View/Home/index.html.twig
  src/View/WhoAreUs/_whoAreUs.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#110 SP5 patch liens event
  src/View/Home/_event.html.twig
Labels: Reviewed

#123 SP05 patch espace vide navbar dans price
  src/View/Price/index.html.twig
Labels: Reviewed

#158 Issues #155 - WAU fix
  src/View/Admin/_whoAreUsAdmin.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
Labels: Reviewed

#160 Issue #111-widtH2
  public/assets/css/style.css
Labels: Reviewed

#161 Issue#131-LessonListSorting
  src/Model/LessonManager.php
Labels: Reviewed

#164 Issues #152 fix style button in WAU
  src/View/WhoAreUs/formWhoAreUs.html.twig
Labels: Reviewed

#165 issue#129_missingBubbles
  .gitignore
  public/assets/images/bulles25-1-l.png
  public/assets/images/bulles25-3-l.png
  src/View/layout.html.twig
Labels: Reviewed

#162 Issue#114&#118-Contact:vs*
  src/View/Contact/index.html.twig
Labels: Reviewed

#166 Issue#121-StageRemove2DotsH1
  src/View/Stage/index.html.twig
Labels: Reviewed

#167 Issues #124 Home page text delete in mobile version
  public/assets/css/homepage.css
  src/View/Home/index.html.twig
Labels: Reviewed

#168 Issues #122 price and WAU page height
  src/View/WhoAreUs/index.html.twig
Labels: Reviewed

#169 issue #142_buttonsSize
  .gitignore
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/addEvent.html.twig
  src/View/Admin/addLesson.html.twig
  src/View/Admin/editLesson.html.twig
  src/View/Admin/showEvent.html.twig
  src/View/Stage/index.html.twig
Labels: Reviewed

#170 Issue#150-IconSelectAdminLesson
  src/View/Admin/_lessonDetails.html.twig
Labels: Reviewed

#171 issue#137-delete useless punctuation
  src/View/Admin/_eventDetails.html.twig
Labels: Reviewed

#174 Issue#173delete post
  public/assets/css/style.css
  src/Controller/AdminActivityController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminLessonController.php
  src/Controller/AdminMessageController.php
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_messageAdmin.html.twig
Labels: Reviewed

#175 Issue#151 lesson form control
  src/Controller/AdminLessonController.php
Labels: Reviewed

#176 Issue#116FormContact
  src/View/Contact/index.html.twig
Labels: Reviewed

#177 issue#153_upload_button_corrected
  public/assets/css/picture_upload.css
  public/assets/css/style.css
  public/assets/js/script.js
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/_pictureUpload.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#178 issue #127_homepageActivityButtonAlignment
  public/assets/css/homepage_activity.css
Labels: Reviewed

#181 issue #128 solved as contact page is now repsonsive
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#179 issue #146_event_form_buttons_aligned
  src/Controller/AdminEventController.php
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/showEvent.html.twig
Labels: Reviewed

#180 issue #132 solved as there is now rthe required label in the form exc…
  src/View/Admin/_eventDetails.html.twig
Labels: Reviewed

#172 Issues#117&#119 contact pages padding
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#189 #issue#148-harmonization button style
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/addLesson.html.twig
  src/View/Admin/editLesson.html.twig
Labels: Reviewed

#190 issue #136 solved, left and right parts of the event form match the a…
  public/assets/css/admin_event.css
  src/View/Admin/_eventDetails.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#192 issue#138-multi-file spell checking
  src/Controller/AdminActivityController.php
  src/View/Admin/addEvent.html.twig
  src/View/Item/show.html.twig
  src/View/WhoAreUs/index.html.twig
Labels: Reviewed

#193 #149FieldFormLesson
  src/View/Admin/_lessonDetails.html.twig
Labels: Reviewed

#197 eventForm restored after having been broken by merge
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/_pictureUpload.html.twig
Labels: Reviewed

#195 Issues#130Activity detail Page Responsivity
  public/assets/css/activity.css
Labels: Reviewed

#191 Issue #140ErrorFormLesson
  src/Controller/AdminLessonController.php
  src/View/Admin/_lessonDetails.html.twig
Labels: Corrections done, Reviewed

#194 Issue#186back button
  public/assets/css/homepage_activity.css
  public/assets/css/style.css
  src/View/Admin/addEvent.html.twig
  src/View/Admin/addLesson.html.twig
  src/View/Admin/formLayout.html.twig
  src/View/Admin/showEvent.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
Labels: Corrections done, Reviewed

#196 issue #141 now impossible de create a pool with an empty name
  src/Controller/AdminLessonController.php
  src/View/Admin/_lessonDetails.html.twig
Labels: Reviewed

#198 issue #188 no possibility to send space to database
  src/Controller/AdminActivityController.php
  src/Controller/AdminEventController.php
Labels: Reviewed

#199 Fix_IssueForms
  src/Controller/AdminActivityController.php
  src/Controller/AdminEventController.php
  src/View/Admin/showEvent.html.twig
Labels: Reviewed

#200 final dev to master
  .gitignore
  public/assets/css/activity.css
  public/assets/css/admin_event.css
  public/assets/css/contact.css
  public/assets/css/homepage.css
  public/assets/css/homepage_activity.css
  public/assets/css/picture_upload.css
  public/assets/css/style.css
  public/assets/images/bulles25-1-l.png
  public/assets/images/bulles25-3-l.png
  public/assets/js/script.js
  src/Controller/AdminActivityController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminLessonController.php
  src/Controller/AdminMessageController.php
  src/Model/LessonManager.php
  src/View/Activity/showActivity.html.twig
  src/View/Admin/_activityAdmin.html.twig
  src/View/Admin/_activityDetails.html.twig
  src/View/Admin/_eventAdmin.html.twig
  src/View/Admin/_eventDetails.html.twig
  src/View/Admin/_lessonAdmin.html.twig
  src/View/Admin/_lessonDetails.html.twig
  src/View/Admin/_messageAdmin.html.twig
  src/View/Admin/_pictureUpload.html.twig
  src/View/Admin/_whoAreUsAdmin.html.twig
  src/View/Admin/addEvent.html.twig
  src/View/Admin/addLesson.html.twig
  src/View/Admin/editLesson.html.twig
  src/View/Admin/formLayout.html.twig
  src/View/Admin/showEvent.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_event.html.twig
  src/View/Home/index.html.twig
  src/View/Item/show.html.twig
  src/View/Price/index.html.twig
  src/View/Stage/index.html.twig
  src/View/WhoAreUs/formWhoAreUs.html.twig
  src/View/WhoAreUs/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed
